### ISSUE TITLE
🔧 [Telemetry] Span & metrics exporting should be disabled by default

### ISSUE THREAD

**Issue by roma-glushko** [EinStack/glide#248] opened 2024-05-06 19:55 UTC
Tracing and metrics should be optional and disabled by default in case people don't have a backend to export them and view:

![2024-05-06_22-52-50](https://github.com/EinStack/glide/assets/9402690/c877a26e-b510-487a-9ee6-2af53d07c241)

**Comment by roma-glushko** [comment] 2024-05-06 19:56
cc @gernest

**Comment by gernest** [comment] 2024-05-06 21:03
Probably you have otel envs setup . Default providers are `none`. which is a noop provider.  Looks like you have otel configured  pointing to `localhost:4314/v1/metrics` ? the port looks like from victoria metrics or something?

You can close this, it is not a glide issue.

**Comment by gernest** [comment] 2024-05-08 18:43
@roma-glushko did you check otel env vars? Just needs to make sure this is not an issue, before I start instrumentation this weekend.

**Comment by roma-glushko** [comment] 2024-05-10 08:58
@gernest I don't think I have any OTEL_* env variables set. This is reproducible when I just start a dev process via `make run` and then execute some workflows like chat requests, then after some time I start seeing this warning. 

In that workflow, I don't any environment variables other than provider's API keys.

**Comment by roma-glushko** [comment] 2024-05-10 09:02
Tracing and metrics should be disabled by default as they require special tools to take advantage of them and we have no assumptions/requirements around users having that in place. If I just install Glide via `brew` and start the process with a simple config, there should no warnings about inability to export metrics or traces and there would no additional environment variables to setup observability (unless the user goes for that after some time playing around with Glide).

**Comment by gernest** [comment] 2024-05-10 11:39
I was able to reproduce this locally, will work on a fix.

**Closed** 2024-05-12 11:52 UTC
Labels: good first issue, area:telemetry, size:small
